### ISSUE TITLE
No puedo hacer git push

### ISSUE THREAD

**Issue by Krmn390** [IIC2433/Syllabus-2021-2#1]
Hola! Mi problema es que al tratar de hacer git push, me sale lo siguiente:
![Captura de Pantalla 2021-08-20 a la(s) 12 55 42](https://user-images.githubusercontent.com/69641719/130271011-b6acae16-1ec4-4556-85bf-d22a748e81c4.png)

Seguí todos los pasos para conectar GitHub a mi clave SSH (que por cierto acabo de crear), pero nada, me sigue saliendo lo mismo. ¿Qué puedo hacer?

**Comment by juanreutter** [comment]
Hola, está bien por que no te tengo con permisos para hacer push. Pero quizás me perdí de algo y te lo tengo que dar: para que necesitas hacer push?

**Comment by Krmn390** [comment]
Jaja lo siento, pregunté cómo se hacían las actividades este semestre, y me dijeron que se hacían clonando el repositorio. Pensé que podíamos subir nuestros avances de las actividades por aquí jeje
