### ISSUE TITLE
[Tarea 3][P2.c] Features escogidas con warnings son válidas?

### ISSUE THREAD

**Issue by cjones27** [IIC2433/Syllabus-2021-2#29]
Hola, ya estoy terminando la tarea pero me surgió una duda. Al momento de escoger las features con el silhouette score como pide el enunciado, me entró la duda si esa feature escogida puede ser escogida a pesar de que no logre clusterizar en los 10 clusters esperados (es decir, tira el warning). Por ejemplo, escogo la feature 89 por silhouette score pero la clusterización con esa feature solo me retorna 7 clusters en vez de 10. Sería válido escoger la feature 89?

Saludos de antemano.

**Comment by juanreutter** [comment]
Si, es valido. No sé si sería válido en la vida real jaja, posiblemente uno debería filtrar adicionalmente dimensiones que tengan al menos 10 puntos distintos, pero eso no es parte de la tarea.
