### ISSUE TITLE
[Actividad 8] Error en graficar Ejercicio 2

### ISSUE THREAD

**Issue by cjones27** [IIC2433/Syllabus-2021-2#30]
Hola, estaba haciendo la actividad 8 y me ocurre un error cuando intento graficar los resultados de hacer DBScan y GMM en mnist_sample(el subset visto en la tarea 3). Entiendo que le estoy pasando un array como llave pero no entiendo por qué ocurre ni como arreglarlo.

Muchas gracias de antemano.

![Screenshot 2021-10-15 at 13 51 24](https://user-images.githubusercontent.com/48262167/137524583-bcb86949-badf-47de-af8e-96f5571007fd.png)

**Comment by amahns1** [comment]
Hola!

No soy ayudante, pero llegué al mismo punto en un momento.
Fíjate que en el enunciado dice: "Concéntrate sólo en el set de datos resultante de reducir la dimensionalidad con T-SNE"

Al final, tienes que adaptar la dimensionalidad de tu nuevo dataset. Aquí dejo la documentación: https://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html

Espero que te sirva :)
