### ISSUE TITLE
Notas y fecha entrega parte 3 proyecto

### ISSUE THREAD

**Issue by josemquinta15** [IIC2433/Syllabus-2021-2#44]
Hola!

Quería saber cuándo se estima que estén las notas de las tareas 4 y 5, ya que me gustaría tener esas notas para decidir si hacer o no la tarea, y no quiero dejar la tarea para el final en el caso de tener que hacerla. 

Además, quería saber cuando es la fecha de entrega de la parte 3 del proyecto, ya que el enunciado dice que es el viernes 18 de diciembre, pero el 18 de diciembre cae sabado... por lo que no me queda claro si la entrega es el viernes o el sabado.

De antemano, gracias

**Comment by juanreutter** [comment]
Hola, las de la 4 bien pronto, nos estamos apurando lo más posible. Las de la 5 van a estar bien encima de la fecha, así que esa info no la vas a tener. 

Tienes toda la razón, no sé por qué está el 18 en el calendario que yo tenía, pensaba que ya no hacen examenes los sabados! 

De cualquier forma, el enunciado ya está y no sería bueno mover la fecha, así que queda para el sabado 18.

**Comment by josemquinta15** [comment]
Genial, muchas gracias
